### ISSUE TITLE
Error on fresh install on Linux

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#312]
```
> library('RDataTracker')
> ddg.init()
> x <- 0
> y <- 1
> z <- x +y
> ddg.save()
[1] "Saving ddg.txt in /home/vagrant/ddg"
[1] "Saving ddg.json in /home/vagrant/ddg"
Warning message:
In .ddg.insert.error.message(error.msg) :
  No binding for ddg.annotate.inside . DDG may be incorrect!
> ddg.display()
laser.ddg.persist.ReportErrorException: "No binding for ddg.annotate.inside . DDG may be incorrect!"
	at laser.ddg.DDGBuilder.addDataProducer(DDGBuilder.java:115)
	at laser.ddg.persist.Parser.addDataProducerEdge(Parser.java:410)
	at laser.ddg.persist.TextParser.parseDataFlowEdge(TextParser.java:767)
	at laser.ddg.persist.TextParser.parseEdge(TextParser.java:743)
	at laser.ddg.persist.TextParser.lambda$0(TextParser.java:716)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at laser.ddg.persist.TextParser.addEdges(TextParser.java:715)
	at laser.ddg.persist.TextParser.parseNodesAndEdges(TextParser.java:136)
	at laser.ddg.persist.Parser.addNodesAndEdges(Parser.java:150)
	at laser.ddg.commands.LoadFileCommand.loadFile(LoadFileCommand.java:61)
	at laser.ddg.gui.DDGExplorer.main(DDGExplorer.java:571)
Jun 20, 2017 8:48:50 PM prefuse.action.ActionList run
WARNING: null
java.lang.NullPointerException
	at laser.ddg.visualizer.DDGLayout.getLayoutRoot(DDGLayout.java:154)
	at laser.ddg.visualizer.DDGLayout.run(DDGLayout.java:111)
	at prefuse.action.ActionList.run(ActionList.java:79)
	at prefuse.action.Action.run(Action.java:122)
	at prefuse.activity.Activity.runActivity(Activity.java:152)
	at prefuse.activity.ActivityManager.run(ActivityManager.java:365)
```

**Comment by blernermhc** [comment]
The ddg.annotate.inside error seems really odd.  That function has been around a long time.  What version of RDT are you using?

**Comment by tfjmp** [comment]
Using Matt tool:
```
Environment
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe               
                                                Package 
                                         "RDataTracker" 
                                                LibPath 
                                 "/usr/lib64/R/library" 
                                                Version 
                                               "2.26.0" 
                                               Priority 
                                                     NA 
                                                Depends 
                                        "R (>= 2.13.0)" 
                                                Imports 
"gtools, XML, knitr, stringr, utils, devtools, methods" 
                                              LinkingTo 
                                                     NA 
                                               Suggests 
                                                     NA 
                                               Enhances 
                                                     NA 
                                                License 
                                 "GPL-3 | file LICENSE" 
                                        License_is_FOSS 
                                                     NA 
                                  License_restricts_use 
                                                     NA 
                                                OS_type 
                                                     NA 
                                                 MD5sum 
                                                     NA 
                                       NeedsCompilation 
                                                     NA 
                                                  Built 
                                                "3.3.3" 
```

This is our current master.

**Comment by tfjmp** [comment]
You can easily reproduce the problem with:
https://github.com/End-to-end-provenance/e2eprov-vagrant

Edit shared/install.sh if you want to build RDataTracker from a different branch.

**Comment by MKLau** [comment]
Check on developmont prior to update of master 2.27.0.

**Comment by blernermhc** [comment]
This works now.
